### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Oxford-G**
A simple web application where the users can have many different projects, add a different task or to-do's for each project and delete or edit projects and to-do. This pull request tests for all the dependencies using jest.

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Git flow is used properly.
## To Improve 🙏
- [ ] Please add `npm run test` command in README. The project user should know all the necessary commands to run the project locally.
- [ ] Please add tests for all the functions. 
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Changes Required ♻️
Hey, @Oxford-G you have done a good job to reach this far. For example, I have seen a change in the readme file indicating how to test the project, but still, there are some changes to make for this project to be approved.

- [ ] There are some methods that should be tested, methods like, removeTodo, updateTodo, etc.

<hr>
Cheers and Happy Coding🎉💪

### If you have any questions, just comment here in this PR, or can always connect with me on slack as Elisha kyakopo.

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, thank you for implementing changes suggested previously :ok_hand:
## To Improve 🙏
- [ ] Please make sure that all the functions are tested.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by cyonii — APPROVED** [review]
### STATUS: APPROVED ✅

Good job implementing the requested changes, your roject is approved.
See you in future reviews.

Happy coding 💻.

> #### <br>Feel free to leave a comment or question if something is not clear.<br> Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)<br><br>

**Pull request merged**
